### ISSUE TITLE
 buildDebug creates two .so files

### ISSUE THREAD

**Issue by dmkif** [RosesTheN00b/gradle-cobol-plugin-core#5]
by building your example with task :buildDebug, the Extension generates two files with different capitalisation.

build
└── bin
└── main
└── cobol
├── HelloWorld.so
├── HELLOWORLD.so
├── HelloWorld.so_COMPILE.LOG
└── HELLOWORLD.so_COMPILE.LOG

Execution of one of the two files ends with an segfault.
Expected behavior only generate on file, that runs :-)

**Comment by SebastianRzk** [comment]
`gradle helloworld && gradle runDebug` and `gradle helloworld && cobcrun -M build/bin/main/cobol/  HELLOWORLD` works on the actual version of the plugin.

Are you sure the folder does not contain two cobol files?

Whats the name of your sourcefile, the content and the error message?

**Comment by dmkif** [comment]
Oh yes ... the source folder contains two source-files ... this happens by executing `gradle helloWorld` in your example-folder. There is a helloWorld.cob already existing. But should the expected behaviour not, to overwrite the source-file when it already existing in src-folder, or i am wrong? 

I attached the output of `gradle helloworld && gradle runDebug`
[error.log](https://github.com/RosesTheN00b/gradle-cobol-plugin-core/files/3151850/error.log)

**Comment by SebastianRzk** [comment]
Fixed with 0d7cdb1217151af05e85ddbc487636d9d53eca30

**Comment by SebastianRzk** [comment]
#11

**Comment by SebastianRzk** [comment]
Closed with 0.0.44
